[package]
name = "shut_the_box"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weighted_rand = "0.4.2"
rand = "0.8.5"
serde = { version = "1.0.198", features = ["derive"] }
serde_yaml = "0.9.33"