[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
# gui
egui = "0.27.2"
egui_extras = "0.27.2"
eframe = "0.27.2"

# misc
compute = { path = "../compute" }
fastrand = "2.1.0"
serde = { version = "1.0.198", features = ["derive"] }
serde_yaml = "0.9.34"